% LAB03_SCAFFOLD.M
% MC3113 Lab 03 — V&V Harness (Student Scaffold)
%
% Your task: implement the five TODO blocks below.
% Do NOT modify any line marked "PROVIDED".
%
% When complete, rename this file to run_harness.m before submitting.
%
% Lab date : 27 March 2026, 13:30–17:30
% Deadline : Soft 18:00 (full marks) | Hard 23:00 (-1 mark per 30 min)
% Marks    : 10  (LO4 — Software Interfaces)
%
% SUBMIT (push to your lab03 branch):
%   run_harness.m          (this file, renamed)
%   lab03_report.json      (generated by your harness)
%   lab03_coverage.csv     (generated by your harness)
%   test_cases.csv         (seed rows + your 2 new test cases)
%
% NOTE: Lab 03 carries its own 10 marks independent of CA3.
%       Your lab mark is not affected by your CA3 submission status.
%
% ─────────────────────────────────────────────────────────────────────────
% PIPELINE ARCHITECTURE
%
%   sensor_stream.bin
%         │
%  [PROVIDED] decode_frames    → decoded table (3741 rows, 3 runs)
%         │
%  TODO 1 load_test_cases      → validated cases table
%         │
%  TODO 2 stimulus_engine      → setpoint profile per test case
%         │  [alignment to log timestamps: PROVIDED]
%         │
%  TODO 3 execute_test         → chamber_temp column appended to log
%         │
%  TODO 4 oracle               → measured metric + verdict + margin
%         │
%  TODO 5 report_generator     → lab03_report.json + lab03_coverage.csv
%
% ─────────────────────────────────────────────────────────────────────────

clear; clc;
fprintf('══════════════════════════════════════════\n');
fprintf('   MC3113 Lab 03 — V&V Harness\n');
fprintf('══════════════════════════════════════════\n\n');

% ═════════════════════════════════════════════════════════════════════════
% PROVIDED — Step 1: Decode the binary sensor stream
% Do NOT modify this block.
% ═════════════════════════════════════════════════════════════════════════
fprintf('[1/5] Decoding sensor stream...\n');
if ~isfile('sensor_stream.bin')
    error('MC3113:FileNotFoundError', ...
        'sensor_stream.bin not found. Check your working folder.');
end
decoded = decode_frames('sensor_stream.bin');
fprintf('      %d valid frames across %d run(s).\n\n', ...
    height(decoded), numel(unique(decoded.run_id)));

% ═════════════════════════════════════════════════════════════════════════
% TODO 1 — Load and validate the test suite
% ═════════════════════════════════════════════════════════════════════════
% Call load_test_cases('test_cases.csv') and assign the result to cases.
% load_test_cases will throw a named error if the file is missing or
% a column is invalid — do not add extra error handling here.
%
% Expected result: cases is a 3×7 table (grows to 5×7 after Task 5).
% ─────────────────────────────────────────────────────────────────────────
fprintf('[2/5] Loading test cases...\n');

% >>> YOUR CODE HERE <<<
cases = load_test_cases('test_cases.csv');  % ← one line; do not change filename

% PROVIDED — guard: catches the unreplaced placeholder
if isempty(cases)
    error('MC3113:EmptyCases', ...
        'cases is empty — check your load_test_cases implementation.');
end
fprintf('      %d test case(s) loaded.\n\n', height(cases));

% ═════════════════════════════════════════════════════════════════════════
% TODO 2, 3, 4 — Run oracle for each test case
% ═════════════════════════════════════════════════════════════════════════
fprintf('[3/5] Running oracle for each test case...\n');

% PROVIDED — pre-allocate results struct array. Do not modify.
results = struct('test_id',{}, 'metric',{}, 'measured',{}, ...
                 'threshold',{}, 'operator',{}, 'verdict',{}, ...
                 'margin',{});

for i = 1:height(cases)
    tc = cases(i, :);

    % --- PROVIDED: extract the correct run slice from decoded ----------
    run_id  = tc.run_id;
    log_raw = decoded(decoded.run_id == run_id, :);

    % --- PROVIDED: build params struct for stimulus engine -------------
    params.t_amb    = log_raw.t_amb_degC(1);
    params.setpoint = log_raw.setpoint_degC(end);
    params.duration = log_raw.t(end);
    params.dt       = median(diff(log_raw.t));

    % --- PROVIDED: infer stimulus type from run data -------------------
    sp_range = max(log_raw.setpoint_degC) - min(log_raw.setpoint_degC);
    if sp_range > 1.0
        stim_type = 'ramp';
    elseif params.setpoint > 85
        stim_type = 'sustained_fault';
    else
        stim_type = 'step';
    end

    % ── TODO 2 — Generate stimulus profile ───────────────────────────
    % Call stimulus_engine(stim_type, params).
    % Assign outputs to [t_arr, sp_arr].
    % >>> YOUR CODE HERE <<<
    [t_arr, sp_arr] = stimulus_engine(stim_type, params);  % ← fill in

    % PROVIDED — align sp_arr onto the decoded log's time axis.
    % (Floating-point rounding means t_arr and log_raw.t may differ by ±1
    %  sample; interp1 corrects this silently.) Do NOT modify.
    log = log_raw;
    log.setpoint_degC = interp1(t_arr, sp_arr, log_raw.t, 'linear', 'extrap');

    % ── TODO 3 — Run the CUT to produce chamber_temp ─────────────────
    %   CRITICAL: Do this BEFORE implementing oracle metrics.
    %   If skipped: chamber_temp does not exist → oracle crashes OR returns
    %   all-zero errors → all margins = +1.0000 → TC-03 returns PASS (wrong).
    %
    % Call execute_test(log) and assign the result back to log.
    % After this line, log.chamber_temp must exist.
    % >>> YOUR CODE HERE <<<

    % ── TODO 4 — Evaluate the oracle ─────────────────────────────────
    % Call oracle(log, tc) and assign the result to res.
    % res must be a struct with fields:
    %   test_id, metric, measured, threshold, operator, verdict, margin
    % >>> YOUR CODE HERE <<<

    % PROVIDED — append result and print summary. Do NOT modify.
    results(end+1) = res; %#ok
    fprintf('   %-6s  %-24s  %-4s  measured=%.4f  margin=%+.4f\n', ...
        char(tc.test_id), char(tc.metric), ...
        res.verdict, res.measured, res.margin);
end
fprintf('\n');

% ═════════════════════════════════════════════════════════════════════════
% TODO 5 — Generate the report
% ═════════════════════════════════════════════════════════════════════════
% Call report_generator(cases, results, 'lab03_report.json', 'lab03_coverage.csv')
% >>> YOUR CODE HERE <<<

% PROVIDED — confirmation message (runs after your report_generator call)
fprintf('[4/5] Report written.\n');

% ═════════════════════════════════════════════════════════════════════════
% PROVIDED — Submission checklist
% ═════════════════════════════════════════════════════════════════════════
fprintf('\n[5/5] Done. Rename this file to run_harness.m, then push:\n');
fprintf('   run_harness.m\n');
fprintf('   lab03_report.json\n');
fprintf('   lab03_coverage.csv\n');
fprintf('   test_cases.csv  (seed rows + your 2 new test cases)\n\n');